// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHvenus_zYVFhR2QjUoMTmxgCmSVZuaY',
    appId: '1:51727607016:web:2f44f66102b50f7624155d',
    messagingSenderId: '51727607016',
    projectId: 'notification-64569',
    authDomain: 'notification-64569.firebaseapp.com',
    storageBucket: 'notification-64569.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJh3zc-lFgrc7Fz3FpTJS3AK0dsigV4Iw',
    appId: '1:51727607016:android:88f3f7afdfd77a9224155d',
    messagingSenderId: '51727607016',
    projectId: 'notification-64569',
    storageBucket: 'notification-64569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFj9gZsyo6DZN1iOefwpb1Gy3Cp6zfyEo',
    appId: '1:51727607016:ios:489eb4af30f0418e24155d',
    messagingSenderId: '51727607016',
    projectId: 'notification-64569',
    storageBucket: 'notification-64569.appspot.com',
    iosBundleId: 'com.techbrothers.flutternotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFj9gZsyo6DZN1iOefwpb1Gy3Cp6zfyEo',
    appId: '1:51727607016:ios:818e266708c78b9324155d',
    messagingSenderId: '51727607016',
    projectId: 'notification-64569',
    storageBucket: 'notification-64569.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );
}
